USE ROLE ACCOUNTADMIN;

-- Set context
USE DATABASE SNOWFLAKE;
-- Account usage view (365 days of query history) but has a lag of a couple of hours
USE SCHEMA ACCOUNT_USAGE;

SELECT * 
FROM ACCOUNT_USAGE.QUERY_HISTORY 
WHERE WAREHOUSE_SIZE IS NOT NULL
ORDER BY TOTAL_ELAPSED_TIME DESC
LIMIT 100;

-- Ten longest running queries in seconds
SELECT 
  QUERY_ID, 
  QUERY_TEXT, 
  USER_NAME, 
  ROLE_NAME,
  EXECUTION_STATUS, 
  ROUND(TOTAL_ELAPSED_TIME / 1000,2) AS TOTAL_ELAPSED_TIME_SEC   
FROM QUERY_HISTORY
WHERE TOTAL_ELAPSED_TIME_SEC > 3
ORDER BY TOTAL_ELAPSED_TIME_SEC DESC
LIMIT 10;

-- INFORMATION_SCHEMA is up to date but query_history only has 7 days of history
SELECT *
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.QUERY_HISTORY())
order by start_time desc;
