USE ROLE SYSADMIN;
USE DATABASE TESTDB;

SELECT * FROM TEST_TABLE;

-- Show products with price < 100
CREATE OR REPLACE ROW ACCESS POLICY CHEAP_PRODUCTS AS (PRICE NUMERIC) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ANALYST') AND PRICE < 100 THEN TRUE
        WHEN CURRENT_ROLE() IN ('ANALYST') AND PRICE >= 100 THEN FALSE
        ELSE TRUE
    END;

ALTER TABLE TEST_TABLE ADD ROW ACCESS POLICY CHEAP_PRODUCTS ON (PRICE);    

USE ROLE ANALYST;

SELECT * FROM TEST_TABLE;

ALTER TABLE TEST_TABLE DROP ROW ACCESS POLICY CHEAP_PRODUCTS;
